#!/usr/bin/env python

import argparse
from os.path import exists
import base64
import json
import subprocess

parser = argparse.ArgumentParser(description='Call peachme.io & get your picture with peach kissing you')
parser.add_argument('image', type=str, help='source image to use')
args = parser.parse_args()

file=args.image

if not exists(file):
    print(f"❌ {file} does not exist.")
    exit(1)

with open(file, "rb") as image_file:
    encoded_string = base64.b64encode(image_file.read())
    DATA = json.dumps({'image': encoded_string.decode("utf-8")})
    import urllib.request
    req = urllib.request.Request(url='http://api.peachme.io:8090/kissme', 
        data=DATA.encode("utf-8"), 
        method='POST',
        headers={
            'Content-Type': 'application/json'
        }
    )
    with urllib.request.urlopen(req) as f:
        raw_data = f.read()
        data = json.loads(raw_data.decode("utf-8"))
        with open("/tmp/output.png", "wb") as out:
            out.write(base64.b64decode(data['image'].split(",")[1]))
        subprocess.run(["open", "/tmp/output.png"])